openapi: 3.0.0
info:
  title: RepoSage Inference API
  version: 1.0.0
servers:
  - url: https://<your-space>.hf.space
paths:
  /query:
    post:
      summary: Ask a question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                threshold:
                  type: number
              required:
                - question
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  confidence:
                    type: number
